version: "2"

services:
  server:
    env_file:
      - ./config/env/.dev.env
    image: python:3.7.3
    working_dir: /sre
    volumes:
      - .:/sre
    ports:
      - 3000:3000
    command: python src/run.py